import { Product, Category } from '../types';

export const FALLBACK_CATEGORIES: Category[] = [
  {
    id: 'cat_food',
    name: 'Food & Meals',
    slug: 'food',
    description: 'Freshly prepared hot canteen meals, biryani & evening snacks'
  },
  {
    id: 'cat_fruits',
    name: 'Fresh Produce',
    slug: 'fruits',
    description: 'Handpicked fresh orchard fruits delivered directly to your room'
  },
  {
    id: 'cat_stationery',
    name: 'Stationery',
    slug: 'stationery',
    description: 'Calculators, engineering notebooks, pens, and lab supplies'
  },
  {
    id: 'cat_essentials',
    name: 'Hostel Essentials',
    slug: 'essentials',
    description: 'Personal care, grooming, cleaning kits, and room necessities'
  },
  {
    id: 'cat_laundry',
    name: 'Express Laundry',
    slug: 'laundry',
    description: 'Automated campus wash, steam press, and room pickup across Halls 1–14'
  },
  {
    id: 'cat_other',
    name: 'Other',
    slug: 'other',
    description: 'Miscellaneous campus student essentials and utilities'
  }
];

export interface ProviderInfo {
  id: string;
  name: string;
  shortName: string;
  category: string;
  rating: number;
}

export const FALLBACK_PROVIDERS: ProviderInfo[] = [
  { id: 'prov_abc', name: 'ABC Provider', shortName: 'ABC', category: 'Food & Meals', rating: 4.8 },
  { id: 'prov_canteen', name: 'Campus Food & Cafeteria Vendor', shortName: 'Canteen', category: 'Food & Meals', rating: 4.7 },
  { id: 'prov_fruits', name: 'Green Basket Campus Fresh Fruits', shortName: 'Green Basket', category: 'Fresh Fruits', rating: 4.9 },
  { id: 'prov_general', name: 'Campus Services Dispatch & Essentials Cell', shortName: 'Essentials', category: 'Stationery & Essentials', rating: 4.8 },
  { id: 'prov_laundry', name: 'Campus Laundry Cell', shortName: 'Laundry', category: 'Express Laundry', rating: 4.9 },
];

export const FALLBACK_STORE_PRODUCTS: Product[] = [
  // 1. Food & Meals (Pure Veg / Non-Veg)
  {
    id: 'prod_momo_veg',
    name: 'Veg Steamed Momo',
    slug: 'veg-steamed-momo',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    providerId: 'prov_abc',
    subcategory: 'Snacks',
    dietaryType: 'Pure Veg',
    isPopular: true,
    description: '6 pieces of fresh steamed vegetable momo stuffed with cabbage, carrots, onion and served with spicy red chili chutney.',
    price: 80,
    originalPrice: 80,
    sellingPrice: 80,
    discountPrice: null,
    discountPercentage: 0,
    unit: 'plate',
    stock: 50,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: true,
    availableToday: true,
    tags: 'momo, veg momo, steamed momo, snacks, pure veg, abc, popular',
    primaryImage: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800',
    rating: 4.8,
    reviewsCount: 38
  },
  {
    id: 'prod_momo_chicken',
    name: 'Chicken Steamed Momo',
    slug: 'chicken-steamed-momo',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    providerId: 'prov_abc',
    subcategory: 'Snacks',
    dietaryType: 'Non-Veg',
    isPopular: true,
    description: '6 pieces of juicy minced chicken steamed momo seasoned with Himalayan spices, served with fiery momo chili sauce.',
    price: 100,
    originalPrice: 100,
    sellingPrice: 100,
    discountPrice: null,
    discountPercentage: 0,
    unit: 'plate',
    stock: 60,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: true,
    availableToday: true,
    tags: 'momo, chicken momo, steamed momo, nonveg, chicken, abc, popular',
    primaryImage: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800',
    rating: 4.9,
    reviewsCount: 52
  },
  {
    id: 'prod_1',
    name: 'Kolkata Style Chicken Biryani',
    slug: 'kolkata-chicken-biryani',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    subcategory: 'Meals',
    dietaryType: 'Non-Veg',
    isPopular: true,
    description: 'Fragrant basmati rice cooked with succulent chicken piece, boiled egg, and golden spiced potato.',
    price: 140,
    originalPrice: 140,
    sellingPrice: 125,
    discountPrice: 125,
    discountPercentage: 11,
    unit: 'plate',
    stock: 45,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: true,
    availableToday: true,
    tags: 'biryani, chicken, meals, nonveg, spicy, popular',
    primaryImage: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800',
    rating: 4.8,
    reviewsCount: 42
  },
  {
    id: 'prod_2',
    name: 'Egg Curry with Steamed Basmati Rice',
    slug: 'egg-curry-rice',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    subcategory: 'Meals',
    dietaryType: 'Non-Veg',
    isPopular: false,
    description: 'Two spiced eggs in home-style tomato-onion gravy served with piping hot steamed rice.',
    price: 80,
    originalPrice: 80,
    sellingPrice: 75,
    discountPrice: 75,
    discountPercentage: 6,
    unit: 'meal',
    stock: 35,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: false,
    availableToday: true,
    tags: 'egg curry, rice, meals, nonveg',
    primaryImage: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800',
    rating: 4.6,
    reviewsCount: 28
  },
  {
    id: 'prod_3',
    name: 'Paneer Butter Masala Combo',
    slug: 'paneer-butter-masala-combo',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    subcategory: 'Meals',
    dietaryType: 'Pure Veg',
    isPopular: true,
    description: 'Rich cottage cheese cubes in buttery creamy tomato gravy served with 3 butter rotis and salad.',
    price: 110,
    originalPrice: 110,
    sellingPrice: 99,
    discountPrice: 99,
    discountPercentage: 10,
    unit: 'combo',
    stock: 25,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: true,
    availableToday: true,
    tags: 'paneer, butter masala, veg, pure veg, meal, roti, popular',
    primaryImage: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800',
    rating: 4.7,
    reviewsCount: 35
  },
  {
    id: 'prod_4',
    name: 'Campus Samosa & Masala Chai Combo',
    slug: 'samosa-chai-combo',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    subcategory: 'Snacks',
    dietaryType: 'Pure Veg',
    isPopular: true,
    description: 'Two crisp golden aloo samosas served with tangy chutney and a steaming cup of ginger masala tea.',
    price: 25,
    originalPrice: 25,
    sellingPrice: 25,
    discountPrice: null,
    discountPercentage: 0,
    unit: 'combo',
    stock: 80,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: false,
    availableToday: true,
    tags: 'samosa, chai, tea, snacks, veg, pure veg, popular',
    primaryImage: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800',
    rating: 4.9,
    reviewsCount: 65
  },
  {
    id: 'prod_9',
    name: 'Kolkata Double Egg Chicken Kathi Roll',
    slug: 'kolkata-chicken-roll',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    subcategory: 'Snacks',
    dietaryType: 'Non-Veg',
    isPopular: true,
    description: 'Flaky paratha layered with double eggs, spiced marinated chicken chunks, sliced onions, and zesty sauce.',
    price: 80,
    originalPrice: 80,
    sellingPrice: 70,
    discountPrice: 70,
    discountPercentage: 13,
    unit: 'roll',
    stock: 60,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: true,
    availableToday: true,
    tags: 'roll, chicken roll, egg, snacks, nonveg, fastfood, popular',
    primaryImage: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800',
    rating: 4.8,
    reviewsCount: 50
  },
  {
    id: 'prod_10',
    name: 'South Indian Crispy Masala Dosa',
    slug: 'masala-dosa',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    subcategory: 'Meals',
    dietaryType: 'Pure Veg',
    isPopular: false,
    description: 'Golden fermented rice crepe filled with spiced potato masala, served with piping hot sambar and fresh chutney.',
    price: 65,
    originalPrice: 65,
    sellingPrice: 55,
    discountPrice: 55,
    discountPercentage: 15,
    unit: 'plate',
    stock: 40,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: false,
    availableToday: true,
    tags: 'dosa, south indian, masala dosa, veg, pure veg',
    primaryImage: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800',
    rating: 4.6,
    reviewsCount: 38
  },

  // 2. Fresh Produce (dietaryType: 'Not Applicable')
  {
    id: 'prod_5',
    name: 'Kashmiri Crisp Apples',
    slug: 'kashmiri-apples',
    categoryId: 'cat_fruits',
    category: FALLBACK_CATEGORIES[1],
    subcategory: 'Fruits',
    dietaryType: 'Not Applicable',
    isPopular: true,
    description: 'Sweet, crisp, and nutrient-dense fresh Kashmiri red apples.',
    price: 150,
    originalPrice: 150,
    sellingPrice: 135,
    discountPrice: 135,
    discountPercentage: 10,
    unit: 'kg',
    stock: 30,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: true,
    availableToday: true,
    tags: 'apples, fruit, kashmiri, fresh produce, healthy, popular',
    primaryImage: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=800',
    rating: 4.7,
    reviewsCount: 22
  },
  {
    id: 'prod_6',
    name: 'Robusta Ripe Bananas',
    slug: 'robusta-bananas',
    categoryId: 'cat_fruits',
    category: FALLBACK_CATEGORIES[1],
    subcategory: 'Fruits',
    dietaryType: 'Not Applicable',
    isPopular: true,
    description: 'Naturally ripened, potassium-rich fresh bananas.',
    price: 60,
    originalPrice: 60,
    sellingPrice: 50,
    discountPrice: 50,
    discountPercentage: 17,
    unit: 'dozen',
    stock: 50,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: false,
    availableToday: true,
    tags: 'bananas, fruit, fresh produce, healthy, popular',
    primaryImage: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800',
    rating: 4.5,
    reviewsCount: 31
  },
  {
    id: 'prod_15',
    name: 'Nagpur Sweet Oranges',
    slug: 'nagpur-sweet-oranges',
    categoryId: 'cat_fruits',
    category: FALLBACK_CATEGORIES[1],
    subcategory: 'Fruits',
    dietaryType: 'Not Applicable',
    isPopular: false,
    description: 'Juicy, vitamin-C packed sweet oranges from Nagpur orchards.',
    price: 90,
    originalPrice: 90,
    sellingPrice: 80,
    discountPrice: 80,
    discountPercentage: 11,
    unit: 'kg',
    stock: 25,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: false,
    availableToday: true,
    tags: 'oranges, citrus, fruit, healthy',
    primaryImage: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=800',
    rating: 4.6,
    reviewsCount: 19
  },

  // 3. Stationery (dietaryType: 'Not Applicable')
  {
    id: 'prod_7',
    name: 'Casio fx-991EX Classwiz Scientific Calculator',
    slug: 'casio-fx-991ex-calculator',
    categoryId: 'cat_stationery',
    category: FALLBACK_CATEGORIES[2],
    subcategory: 'Calculators',
    dietaryType: 'Not Applicable',
    isPopular: true,
    description: 'High-resolution LCD display, 552 functions, matrix, vector, integration for engineering students.',
    price: 1350,
    originalPrice: 1350,
    sellingPrice: 1250,
    discountPrice: 1250,
    discountPercentage: 7,
    unit: 'piece',
    stock: 12,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: true,
    availableToday: true,
    tags: 'calculator, casio, fx991ex, engineering, stationery, popular',
    primaryImage: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=800',
    rating: 5.0,
    reviewsCount: 78
  },
  {
    id: 'prod_8',
    name: 'Classmate Hardbound Exercise Notebook (180 pgs)',
    slug: 'classmate-long-notebook',
    categoryId: 'cat_stationery',
    category: FALLBACK_CATEGORIES[2],
    subcategory: 'Notebooks',
    dietaryType: 'Not Applicable',
    isPopular: true,
    description: 'Smooth ozone-treated elemental chlorine-free paper, ruled, ideal for engineering lectures.',
    price: 70,
    originalPrice: 70,
    sellingPrice: 60,
    discountPrice: 60,
    discountPercentage: 14,
    unit: 'book',
    stock: 100,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: false,
    availableToday: true,
    tags: 'notebook, classmate, stationery, ruled, popular',
    primaryImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800',
    rating: 4.7,
    reviewsCount: 45
  },
  {
    id: 'prod_13',
    name: 'A4 75 GSM High-Speed Copier Paper (Pack of 100)',
    slug: 'a4-copier-paper-100',
    categoryId: 'cat_stationery',
    category: FALLBACK_CATEGORIES[2],
    subcategory: 'Art Supplies',
    dietaryType: 'Not Applicable',
    isPopular: false,
    description: 'Bright white 75 GSM paper for laboratory reports, term papers, and thesis printing.',
    price: 95,
    originalPrice: 95,
    sellingPrice: 85,
    discountPrice: 85,
    discountPercentage: 11,
    unit: 'pack',
    stock: 40,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: false,
    availableToday: true,
    tags: 'paper, a4, printing, lab report, stationery',
    primaryImage: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800',
    rating: 4.8,
    reviewsCount: 30
  },
  {
    id: 'prod_14',
    name: 'Omega Engineering Mini Drafter & Scale Set',
    slug: 'engineering-mini-drafter',
    categoryId: 'cat_stationery',
    category: FALLBACK_CATEGORIES[2],
    subcategory: 'Art Supplies',
    dietaryType: 'Not Applicable',
    isPopular: true,
    description: 'Heavy duty unbreakable engineering drawing drafter for ED / CE / ME graphics labs.',
    price: 450,
    originalPrice: 450,
    sellingPrice: 399,
    discountPrice: 399,
    discountPercentage: 11,
    unit: 'kit',
    stock: 15,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: true,
    availableToday: true,
    tags: 'drafter, engineering drawing, graphics, stationery, popular',
    primaryImage: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800',
    rating: 4.9,
    reviewsCount: 39
  },

  // 4. Hostel Essentials (dietaryType: 'Not Applicable')
  {
    id: 'prod_17',
    name: 'Dettol Antiseptic Liquid & Soap Hygiene Pack',
    slug: 'dettol-hygiene-pack',
    categoryId: 'cat_essentials',
    category: FALLBACK_CATEGORIES[3],
    subcategory: 'Personal Care',
    dietaryType: 'Not Applicable',
    isPopular: true,
    description: 'Essential disinfectant antiseptic liquid (250ml) plus antibacterial bath bar for hostel sanitation.',
    price: 165,
    originalPrice: 165,
    sellingPrice: 145,
    discountPrice: 145,
    discountPercentage: 12,
    unit: 'combo',
    stock: 40,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: true,
    availableToday: true,
    tags: 'dettol, soap, hygiene, essentials, hostel, personal care, popular',
    primaryImage: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800',
    rating: 4.9,
    reviewsCount: 44
  },
  {
    id: 'prod_18',
    name: 'Surf Excel Matic Liquid Detergent & Scrub Kit',
    slug: 'surf-excel-detergent-kit',
    categoryId: 'cat_essentials',
    category: FALLBACK_CATEGORIES[3],
    subcategory: 'Cleaning',
    dietaryType: 'Not Applicable',
    isPopular: false,
    description: 'Top load / bucket wash fabric care liquid (500ml) with dual scrub pad for hostel self-wash.',
    price: 130,
    originalPrice: 130,
    sellingPrice: 115,
    discountPrice: 115,
    discountPercentage: 12,
    unit: 'bottle',
    stock: 35,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: false,
    availableToday: true,
    tags: 'detergent, surf excel, cleaning, essentials, hostel',
    primaryImage: 'https://images.unsplash.com/photo-1585670210693-e7fdd16b142e?w=800',
    rating: 4.7,
    reviewsCount: 29
  },
  {
    id: 'prod_19',
    name: 'Campus Mosquito Repellent Vaporizer & Refill',
    slug: 'mosquito-vaporizer-refill',
    categoryId: 'cat_essentials',
    category: FALLBACK_CATEGORIES[3],
    subcategory: 'Daily Essentials',
    dietaryType: 'Not Applicable',
    isPopular: true,
    description: 'All-night dual-mode mosquito liquid vaporizer machine plus 45-night refill for peaceful hostel study nights.',
    price: 120,
    originalPrice: 120,
    sellingPrice: 99,
    discountPrice: 99,
    discountPercentage: 18,
    unit: 'pack',
    stock: 60,
    isLowStock: false,
    isOutOfStock: false,
    availability: true,
    isFeatured: true,
    availableToday: true,
    tags: 'mosquito, goodknight, vaporizer, essentials, hostel, popular',
    primaryImage: 'https://images.unsplash.com/photo-1628102491329-87364d9fa24d?w=800',
    rating: 4.8,
    reviewsCount: 52
  }
];
