import { Product, Category } from '../types';

export const FALLBACK_CATEGORIES: Category[] = [
  {
    id: 'cat_food',
    name: 'Food & Meals',
    slug: 'food',
    description: 'Freshly prepared hot canteen meals, biryani & evening snacks'
  },
  {
    id: 'cat_fruits',
    name: 'Fresh Fruits',
    slug: 'fruits',
    description: 'Handpicked fresh orchard fruits delivered directly to your room'
  },
  {
    id: 'cat_laundry',
    name: 'Express Laundry',
    slug: 'laundry',
    description: 'Automated campus wash, steam press, and room pickup across Halls 1–14'
  },
  {
    id: 'cat_essentials',
    name: 'Stationery & Essentials',
    slug: 'essentials',
    description: 'Casio scientific calculators, exercise notebooks & lab printing paper'
  }
];

export const FALLBACK_STORE_PRODUCTS: Product[] = [
  // Food & Meals
  {
    id: 'prod_1',
    name: 'Kolkata Style Chicken Biryani',
    slug: 'kolkata-chicken-biryani',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    description: 'Fragrant basmati rice cooked with succulent chicken piece, boiled egg, and golden spiced potato.',
    price: 140,
    discountPrice: 125,
    unit: 'plate',
    stock: 45,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: true,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800',
    rating: 4.8,
    reviewsCount: 42
  },
  {
    id: 'prod_2',
    name: 'Egg Curry with Steamed Basmati Rice',
    slug: 'egg-curry-rice',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    description: 'Two spiced eggs in home-style tomato-onion gravy served with piping hot steamed rice.',
    price: 80,
    discountPrice: 75,
    unit: 'meal',
    stock: 35,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: false,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800',
    rating: 4.6,
    reviewsCount: 28
  },
  {
    id: 'prod_3',
    name: 'Paneer Butter Masala Combo',
    slug: 'paneer-butter-masala-combo',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    description: 'Rich cottage cheese cubes in buttery creamy tomato gravy served with 3 butter rotis and salad.',
    price: 110,
    discountPrice: 99,
    unit: 'combo',
    stock: 25,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: true,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800',
    rating: 4.9,
    reviewsCount: 36
  },
  {
    id: 'prod_4',
    name: 'Campus Samosa & Masala Chai Combo',
    slug: 'samosa-chai-combo',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    description: 'Two crisp golden aloo samosas served with tangy chutney and a steaming cup of ginger masala tea.',
    price: 25,
    discountPrice: null,
    unit: 'combo',
    stock: 80,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: false,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800',
    rating: 4.7,
    reviewsCount: 55
  },
  {
    id: 'prod_5',
    name: 'Crispy Masala Dosa with Chutney & Sambar',
    slug: 'masala-dosa-combo',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    description: 'Crispy fermented rice crepe filled with spiced mashed potato served with fresh coconut chutney and piping hot sambar.',
    price: 65,
    discountPrice: 55,
    unit: 'plate',
    stock: 40,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: true,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800',
    rating: 4.8,
    reviewsCount: 31
  },
  {
    id: 'prod_6',
    name: 'Double Egg Chicken Kathi Roll',
    slug: 'chicken-kathi-roll',
    categoryId: 'cat_food',
    category: FALLBACK_CATEGORIES[0],
    description: 'Flaky paratha layered with twin beaten eggs, spiced grilled chicken pieces, sliced onions, green chillies & lime.',
    price: 85,
    discountPrice: 79,
    unit: 'roll',
    stock: 50,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: true,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800',
    rating: 4.9,
    reviewsCount: 64
  },

  // Fresh Fruits
  {
    id: 'prod_7',
    name: 'Kashmiri Crisp Apples',
    slug: 'kashmiri-apples',
    categoryId: 'cat_fruits',
    category: FALLBACK_CATEGORIES[1],
    description: 'Sweet, crisp, and nutrient-dense fresh Kashmiri red apples hand-selected for campus students.',
    price: 150,
    discountPrice: 135,
    unit: 'kg',
    stock: 30,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: true,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=800',
    rating: 4.8,
    reviewsCount: 22
  },
  {
    id: 'prod_8',
    name: 'Robusta Ripe Bananas',
    slug: 'robusta-bananas',
    categoryId: 'cat_fruits',
    category: FALLBACK_CATEGORIES[1],
    description: 'Naturally ripened, potassium-rich fresh bananas. Perfect quick energy booster before lectures or gym.',
    price: 60,
    discountPrice: 50,
    unit: 'dozen',
    stock: 50,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: false,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800',
    rating: 4.7,
    reviewsCount: 34
  },
  {
    id: 'prod_9',
    name: 'Nagpur Sweet Oranges',
    slug: 'nagpur-oranges',
    categoryId: 'cat_fruits',
    category: FALLBACK_CATEGORIES[1],
    description: 'Juicy, vitamin-C packed sweet oranges from Nagpur orchards. Great for immunity and refreshing hydration.',
    price: 90,
    discountPrice: 80,
    unit: 'kg',
    stock: 25,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: false,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=800',
    rating: 4.6,
    reviewsCount: 19
  },
  {
    id: 'prod_10',
    name: 'Ruby Red Pomegranate',
    slug: 'ruby-pomegranate',
    categoryId: 'cat_fruits',
    category: FALLBACK_CATEGORIES[1],
    description: 'Nutrient-rich, seed-plump juicy rubies bursting with antioxidants and vitamins for hostel wellness.',
    price: 180,
    discountPrice: 165,
    unit: 'kg',
    stock: 20,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: true,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1541344999736-83eca272f6fc?w=800',
    rating: 4.9,
    reviewsCount: 15
  },

  // Stationery & Essentials
  {
    id: 'prod_11',
    name: 'Casio fx-991EX Classwiz Scientific Calculator',
    slug: 'casio-fx-991ex-calculator',
    categoryId: 'cat_essentials',
    category: FALLBACK_CATEGORIES[3],
    description: 'High-resolution LCD display, 552 functions, matrix, vector, integration for engineering students.',
    price: 1350,
    discountPrice: 1250,
    unit: 'piece',
    stock: 12,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: true,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=800',
    rating: 5.0,
    reviewsCount: 78
  },
  {
    id: 'prod_12',
    name: 'Classmate Hardbound Long Exercise Notebook (180 pgs)',
    slug: 'classmate-long-notebook',
    categoryId: 'cat_essentials',
    category: FALLBACK_CATEGORIES[3],
    description: 'Smooth ozone-treated elemental chlorine-free paper, ruled, ideal for engineering lectures.',
    price: 70,
    discountPrice: 60,
    unit: 'book',
    stock: 100,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: false,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800',
    rating: 4.7,
    reviewsCount: 45
  },
  {
    id: 'prod_13',
    name: 'A4 75 GSM High-Speed Copier Paper (Pack of 100)',
    slug: 'a4-copier-paper-100',
    categoryId: 'cat_essentials',
    category: FALLBACK_CATEGORIES[3],
    description: 'Bright white 75 GSM paper for laboratory reports, term papers, and thesis printing.',
    price: 95,
    discountPrice: 85,
    unit: 'pack',
    stock: 40,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: false,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800',
    rating: 4.8,
    reviewsCount: 30
  },
  {
    id: 'prod_14',
    name: 'Omega Engineering Mini Drafter & Scale Set',
    slug: 'engineering-mini-drafter',
    categoryId: 'cat_essentials',
    category: FALLBACK_CATEGORIES[3],
    description: 'Heavy duty unbreakable engineering drawing drafter for ED / CE / ME graphics labs.',
    price: 450,
    discountPrice: 420,
    unit: 'kit',
    stock: 15,
    isLowStock: false,
    isOutOfStock: false,
    isFeatured: true,
    availableToday: true,
    primaryImage: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800',
    rating: 4.9,
    reviewsCount: 39
  }
];
